name: tests

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 12 * * 0" # run once a week on Sunday

jobs:
  build:
    strategy:
      matrix:
        config:
          - ["Py3.9-Plone6.0", "3.9", "6.0"]
          - ["Py3.13-Plone6.0", "3.13", "6.0"]
          - ["Py3.11-Plone6.1", "3.11", "6.1"]
          - ["Py3.13-Plone6.1", "3.13", "6.1"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[0] }}
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: jamescurtin/isort-action@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config[1] }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            **/eggs
            **/downloads
          key: ${{ runner.os }}-cache-${{ hashFiles('setup.*', '*.cfg') }}-${{ matrix.config[0] }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Install dependencies
        run: |
          pip install virtualenv
          virtualenv -p `which python` .
          bin/pip install -r requirements-${{ matrix.config[2] }}.txt
          bin/buildout -c .github-${{ matrix.config[2] }}.cfg
      - name: Test
        run: |
          bin/code-analysis
          bin/test --all
          bin/createcoverage
          bin/coverage report --fail-under=85
